### ISSUE TITLE
Questionable references to suicide and massacre in ktm help

### ISSUE THREAD

**Issue by adamish** [moos-ivp/svn-mirror#1]
Minor point but not sure whether the tone in this help is appropriate in https://github.com/moos-ivp/svn-mirror/blob/2d5f512bea1912d93e14872dde858c59d03a4835/MOOS_Dec3120/MOOSCore/Core/tools/ktm/ktm.cpp

```
    std::cerr<<"Kill The MOOS (ktm)\n";
    std::cerr<<"--channel=<address>    address to issue kill on \n";
    std::cerr<<"--port=<int>           port to issue kill on \n";
    std::cerr<<"--phrase=<string>      pass phrase which Suicide listeners are keyed to\n";
    std::cerr<<"--all                  pass to network, it is a massacre\n";
    std::cerr<<"--query                find out who would jump\n";
    std::cerr<<"--name=<string>        only apply if matches pattern\n";
    std::cerr<<"example    \n";
    std::cerr<<"    ./ktm  --phrase=\"die now\""<<"\n";
```

**Comment by HeroCC** [comment]
Hi Adam, thanks for the input. The code you are referencing is a mirror of the upstream moos project (whereas this is moos-ivp). Specifically, the code is in [core-moos](https://github.com/themoos/core-moos). We generally do not modify upstream code in our tree, so I'd suggest you make a ticket over there. If they change their code, we will update ours correspondingly. Thanks!
